version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DSN=host=postgres port=5432 user=postgres password=password dbname=app_db sslmode=disable
    ports:
      - "8001:8001"

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db