// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login to FamTrust",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Authentication"
                ],
                "summary": "Login to FamTrust",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "User Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponse200"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError500"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve User Profile Details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Profiles"
                ],
                "summary": "Retrieve User Profile Details",
                "operationId": "profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.profileSampleResponse200"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError500"
                        }
                    }
                }
            }
        },
        "/validate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validate User Login Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User-Authentication"
                ],
                "summary": "Validate User Login Token",
                "operationId": "validate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.validateSampleResponse200"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginSampleResponseError500"
                        }
                    }
                }
            }
        },
        "/verify-bvn": {
            "get": {
                "description": "Verify User Signup BVN",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verifications"
                ],
                "summary": "Verify User Signup BVN",
                "operationId": "verify-bvn",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "BVN",
                        "name": "bvn",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/verify-email": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send User-Email Verification Email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verifications"
                ],
                "summary": "Send User-Email Verification Email",
                "operationId": "send-verify-email",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/verify-email/verify": {
            "get": {
                "description": "Verify User Email Address via Token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verifications"
                ],
                "summary": "Verify User Email Address via Token",
                "operationId": "verify-email-code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email verification Token",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/verify-nin": {
            "get": {
                "description": "Verify User Signup NIN",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verifications"
                ],
                "summary": "Verify User Signup NIN",
                "operationId": "verify-nin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "NIN",
                        "name": "nin",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.loginSampleResponse200": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "User Logged in successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 200
                },
                "token": {
                    "type": "string",
                    "example": "b6d4a7e1d2d841a1afe874a2a5c15d8b"
                }
            }
        },
        "handlers.loginSampleResponseError401": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid Credentials"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 401
                }
            }
        },
        "handlers.loginSampleResponseError500": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "An error occured"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "handlers.profileSampleResponse200": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "profile": {
                            "type": "object",
                            "properties": {
                                "bio": {
                                    "type": "string",
                                    "example": "The best FamTrust user of all time."
                                },
                                "bvn": {
                                    "type": "integer",
                                    "example": 35473783473
                                },
                                "createdAt": {
                                    "type": "string",
                                    "example": "2024-07-22T14:30:00Z"
                                },
                                "firstName": {
                                    "type": "string",
                                    "example": "Famtrust"
                                },
                                "id": {
                                    "type": "string",
                                    "example": "a5c9f82e-6b7a-4a53-a81c-82b1e2f453a6"
                                },
                                "lastName": {
                                    "type": "string",
                                    "example": "Guru"
                                },
                                "nin": {
                                    "type": "integer",
                                    "example": 35473745433
                                },
                                "profile_picture_url": {
                                    "type": "string",
                                    "example": "https://image.famtrust.biz/dkkjieikdjfoej.jpg"
                                },
                                "updatedAt": {
                                    "type": "string",
                                    "example": "2024-07-22T14:30:00Z"
                                },
                                "userID": {
                                    "type": "string",
                                    "example": "d38f91b2-dc3b-4f9d-aeb4-7b95c91e9d08"
                                }
                            }
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Request successful"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 200
                },
                "token": {
                    "type": "string",
                    "example": "b6d4a7e1d2d841a1afe874a2a5c15d8b"
                }
            }
        },
        "handlers.validateSampleResponse200": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "user": {
                            "$ref": "#/definitions/handlers.validateSampleResponse200User"
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Request successful"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 200
                },
                "token": {
                    "type": "string",
                    "example": "b6d4a7e1d2d841a1afe874a2a5c15d8b"
                }
            }
        },
        "handlers.validateSampleResponse200User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "has2FA": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "d38f91b2-dc3b-4f9d-aeb4-7b95c91e9d08"
                },
                "isFreezed": {
                    "type": "boolean",
                    "example": true
                },
                "isVerified": {
                    "type": "boolean",
                    "example": true
                },
                "lastLogin": {
                    "type": "string",
                    "example": "2024-07-22T14:30:00Z"
                },
                "role": {
                    "$ref": "#/definitions/handlers.validateSampleResponseRole"
                }
            }
        },
        "handlers.validateSampleResponseRole": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "admin"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "canTransact",
                        " canWithdraw"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "FamTrust API Backend - Auth",
	Description:      "This is the Authentication and Authrization micro-service for the FamTrust Web App.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
