name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Make Inventory
        working-directory: ./deploy
        run: |
          echo "[server]" > ./inventory.ini
          echo "$SERVER_IP" >> ./inventory.ini
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Run Ansible Playbook
        working-directory: ./deploy
        run: |
          ansible-playbook playbook.yaml
